version: '3.8'

services:
  app:
  container_name: myapp
  build:
  volumes:
    - .:/var/www/html

webserver:
  image: nginx:latest
  container_name: nginx_server
  ports:
    - "80:80"
  volumes:
    - .:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - app
  networks:
    - app_network

db:
  image: mysql:8
  container_name: mysql_db
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 
    MYSQL_DATABASE: email_collector
    MYSQL_USER: root
    MYSQL_PASSWORD:
  ports:
    - "3306:3306"
  volumes:
    - db_data:/var/lib/mysql
  networks:
    - app_network

networks:
  app_network:

volumes:
  db_data: