version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: myapp
    build:
      context: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: email_collector
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:


volumes:
  db_data:
